### PR TITLE
Let admins revert withdrawals and awards, and delete records

### PR DESCRIPTION
**Pull request by edwardhorsford**
This adds the ability for admins to undo a withdrawal and remove a QTS or EYTS award. It also adds the ability to delete records.

## Removing a QTS or EYTS award.

A new action line is added to the outcome summary card:
Screenshot 2023-02-27 at 17 11 36

This leads to an instruction page:
Screenshot 2023-02-27 at 17 11 59

At this point, we check with DQT and do not let the admin proceed until DQT has been updated:
Screenshot 2023-02-27 at 17 12 27

Once DQT has been updated, we collect some further information:
Screenshot 2023-02-27 at 17 28 53

Show a confirmation page:
Screenshot 2023-02-27 at 17 14 55

After confirmation, a flash message is shown:
Screenshot 2023-02-27 at 17 17 07

And the action is confirmed in the timeline:
Screenshot 2023-02-27 at 17 19 48
Note the author should be attributed to the DfE admin, not the provider.

## Undoing a withdrawal.

This is a similar flow to undoing the QTS award, except we do not need to check with DQT.

Screenshot 2023-02-27 at 17 21 00
Screenshot 2023-02-27 at 17 21 13
Screenshot 2023-02-27 at 17 21 24
Screenshot 2023-02-27 at 17 21 45
Screenshot 2023-02-27 at 17 30 02

Screenshot 2023-02-27 at 17 30 09

## Deleting a trainee record

This is available where the record is not awarded.

A delete link is added to the admin tab:
Screenshot 2023-02-27 at 17 23 14

Screenshot 2023-02-27 at 17 23 29

Screenshot 2023-02-27 at 17 23 49
Screenshot 2023-02-27 at 17 24 03

### CODE REVIEW

**Comment by edwardhorsford** [comment]
[Design to allow support to un-withdraw a trainee](https://trello.com/c/jKPnytwP/5252-design-to-allow-support-to-un-withdraw-a-trainee)

**Comment by edwardhorsford** [comment]
[Design to allow support to un-award a trainee](https://trello.com/c/YqpUWJaO/5253-design-to-allow-support-to-un-award-a-trainee)

**Comment by edwardhorsford** [comment]
[Design to allow Support to delete a trainee record](https://trello.com/c/NqcPgy52/5254-design-to-allow-support-to-delete-a-trainee-record)

**Comment by claire-hughez** [comment]
On the both flows, what is the reasoning behind the withdrawal or award details being in the admin tab, as opposed to in the 'About their teacher training' section?

_Withdrawals cannot be reverted where the trainee will be **returning** to a new course._ 
I think 'returning' is potentially confusing here. I think 'starting' is probably more helpful?

Otherwise looks great like I said on Slack :D

**Comment by edwardhorsford** [comment]
> On the both flows, what is the reasoning behind the withdrawal or award details being in the admin tab, as opposed to in the 'About their teacher training' section?
> 
> _Withdrawals cannot be reverted where the trainee will be **returning** to a new course._ I think 'returning' is potentially confusing here. I think 'starting' is probably more helpful?
> 
> Otherwise looks great like I said on Slack :D

My thinking is I'd like to try to keep 'adminy' actions away from regular records areas and in the admin section. It is a bit duplicative though. Ideally the admin view wouldn't be the same as regular users, but by accident that's what we've ended up with.

**Comment by claire-hughez** [comment]
_My thinking is I'd like to try to keep 'adminy' actions away from regular records areas and in the admin section._
I don't have a super strong opinion, but given all other changes to the trainee record happen on the actual record (e.g. changing a birthdate), I feel like this is a bit more confusing to Support. I would currently go to the withdrawal bit to change the withdrawal date for example.

**Pull request merged**
