### PR TITLE
Improve page load times

### PR DESCRIPTION
**Pull request by AbigailMcP**
Just testing some things out!

### CODE REVIEW

**Comment by AbigailMcP** [comment]
@edwardhorsford it's still quite slow, but:

Loading trainee index down from 522ms -> 174ms
Loading an individual trainee down from 318ms -> 81.5ms

**Review by edwardhorsford — APPROVED** [review]

**Comment by edwardhorsford** [comment]
@AbigailMcP thanks so much for looking at this!

**Comment by edwardhorsford** [comment]
Do you think there's a similar thing to do for the `shared-record-routes.js` where we read in the schools data?

**Comment by AbigailMcP** [comment]
> Do you think there's a similar thing to do for the `shared-record-routes.js` where we read in the schools data?

Short answer: yes!

Long answer: yes, but I just attempted a refactor and broke everything 😂 - I'm going to merge this in as an incremental improvement and park the second bit for now.

**Pull request merged**
